### ISSUE TITLE
Sodaq MQTT library: packet length greater than 128?

### ISSUE THREAD

**Issue by maxperaltavallejo** [SodaqMoja/Sodaq_MQTT#1]
Hello, I am working on a Wireless Sensor Network, using Autonomo and GPRSBee Rev.6 (Sim800H). I am trying to send data using MQTT library (Sodaq MQTT) to a broker, but so far I can only send packets with a maximun lenght of 128 bytes. I set the MQTT_MAX_PACKET_LENGTH to 180 in the Sodaq_MQTT.h file but I do not know how to modify the cpp file to get it working.

**Comment by MarconiLab** [comment]
I'm with the same problem! How could be increased the MQTT_MAX_PACKET_LENGTH over 128 bytes?
